-- MySQL Script generated by MySQL Workbench
-- Mon Aug 31 11:28:06 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_aeroporto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_aeroporto` ;

-- -----------------------------------------------------
-- Schema bd_aeroporto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_aeroporto` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `bd_aeroporto` ;

-- -----------------------------------------------------
-- Table `AERONAVE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AERONAVE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `AERONAVE` (
  `id_AERONAVE` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(50) NOT NULL,
  `capacidade` INT NOT NULL,
  PRIMARY KEY (`id_AERONAVE`),
  CONSTRAINT `chk_capacidade_positiva` CHECK (`capacidade` > 0))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PASSAGEIRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PASSAGEIRO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PASSAGEIRO` (
  `id_PASSAGEIRO` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_PASSAGEIRO`),
  CONSTRAINT `cpf_UNIQUE` UNIQUE (`cpf`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TELEFONE_PASSAGEIRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TELEFONE_PASSAGEIRO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TELEFONE_PASSAGEIRO` (
  `id_TELEFONE` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(15) NOT NULL,
  `id_PASSAGEIRO` INT NOT NULL,
  PRIMARY KEY (`id_TELEFONE`),
  CONSTRAINT `fk_TELEFONE_PASSAGEIRO`
    FOREIGN KEY (`id_PASSAGEIRO`)
    REFERENCES `PASSAGEIRO` (`id_PASSAGEIRO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `VOO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VOO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `VOO` (
  `id_VOO` INT NOT NULL AUTO_INCREMENT,
  `num_voo` VARCHAR(45) NOT NULL,
  `origem` VARCHAR(100) NOT NULL,
  `destino` VARCHAR(100) NOT NULL,
  `dia_horario` DATETIME NOT NULL,
  `id_AERONAVE` INT NOT NULL,
  PRIMARY KEY (`id_VOO`),
  CONSTRAINT `unq_voo_horario` UNIQUE (`num_voo`, `dia_horario`),
  CONSTRAINT `chk_origem_destino_diferentes` CHECK (`origem` <> `destino`),
  CONSTRAINT `fk_voo_aeronave`
    FOREIGN KEY (`id_AERONAVE`)
    REFERENCES `AERONAVE` (`id_AERONAVE`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
    ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;