-- MySQL Script generated by MySQL Workbench
-- Wed Aug 26 10:58:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_aeroporto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_aeroporto` ;

-- -----------------------------------------------------
-- Schema bd_aeroporto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_aeroporto` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `bd_aeroporto` ;

-- -----------------------------------------------------
-- Table `AERONAVE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AERONAVE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `AERONAVE` (
  `id_AERONAVE` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(50) NOT NULL,
  `capacidade` INT NOT NULL,
  PRIMARY KEY (`id_AERONAVE`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PASSAGEIRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PASSAGEIRO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PASSAGEIRO` (
  `id_PASSAGEIRO` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_PASSAGEIRO`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `cpf_UNIQUE` ON `PASSAGEIRO` (`cpf` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `VOO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VOO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `VOO` (
  `id_VOO` INT NOT NULL AUTO_INCREMENT,
  `num_voo` VARCHAR(45) NOT NULL,
  `origem` VARCHAR(100) NOT NULL,
  `destino` VARCHAR(100) NOT NULL,
  `dia_horario` DATETIME NOT NULL,
  `id_aeronave` INT NOT NULL,
  PRIMARY KEY (`id_VOO`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
